#!/usr/bin/env bash
# GENERATED by `ggen sync` from packs/platform-engineers-handbook-ch02-cluster-pack/ontology.ttl
# -- do not edit by hand. App-of-Apps GitOps bootstrap invocation, matching the source and
# path conventions of Ch02's real modules/flux.py (FluxSourceConfig / FluxAppOfAppsManager.
# create_root_application()). Whether this script performs a real bootstrap or a documented
# no-op is bound from pech2:fluxBootstrapped -- never hand-edited here.
set -euo pipefail

CLUSTER_NAME="platform-eng-colima"

echo "Flux bootstrap SKIPPED for ${CLUSTER_NAME} (pech2:fluxBootstrapped=false in ontology.ttl)."
echo "This environment's cluster-foundation render intentionally omits GitOps wiring --"
echo "see pech2:fluxBootstrapped's rdfs:comment in ontology.ttl for why."
