#!/usr/bin/env bash
# GENERATED by `ggen sync` from packs/platform-engineers-handbook-ch02-cluster-pack/ontology.ttl
# -- do not edit by hand. Mesh-wide STRICT/PERMISSIVE mTLS PeerAuthentication shape adapted
# verbatim from Ch02's real /tmp/platform-engineers-handbook-src/Ch02/istio-mesh-config.yaml
# (`PeerAuthentication`/`name: default`/`namespace: istio-system`). Ch02's own comment notes
# Istio is normally installed via Flux HelmRelease (platform-services.yaml); this script is
# the istioctl-equivalent path for environments (like local Kind iteration loops) that install
# directly instead of waiting on a Flux reconcile. Profile and mTLS mode below are bound from
# this pack's ontology -- never hand-edited here.
set -euo pipefail

CLUSTER_NAME="platform-eng-colima"
ISTIO_PROFILE="minimal"

echo "Installing Istio (profile=${ISTIO_PROFILE}) into kind cluster ${CLUSTER_NAME}..."
istioctl install --context "kind-${CLUSTER_NAME}" --set profile="${ISTIO_PROFILE}" -y

kubectl --context "kind-${CLUSTER_NAME}" label namespace application istio-injection=enabled --overwrite

cat <<'EOF' | kubectl --context "kind-${CLUSTER_NAME}" apply -f -
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: PERMISSIVE
EOF

echo "Istio mesh (profile=${ISTIO_PROFILE}, mtls=PERMISSIVE) ready on ${CLUSTER_NAME}."
