//! FIBO alignment courts. Real collaborators: the real pinned FIBO corpus on disk, the real
//! ggen-generated table, and a really settled payment. No mocks.
mod common;
use common::payments::*;

use castle::payments::fibo::*;
use castle::payments::*;
use sha2::{Digest, Sha256};

fn corpus_root() -> std::path::PathBuf {
    let root = std::env::var("CASTLE_FIBO_CORPUS")
        .unwrap_or_else(|_| "/Users/sac/ggen-marketplace/ontologies/public/fibo".to_string());
    let p = std::path::PathBuf::from(root);
    assert!(p.is_dir(), "FIBO corpus missing at {p:?} (set CASTLE_FIBO_CORPUS); refusing to skip");
    p
}

fn local_name(iri: &str) -> &str {
    iri.rsplit('/').next().unwrap()
}

#[test]
fn drift_court_every_verified_iri_is_defined_in_the_pinned_corpus() {
    let root = corpus_root();
    for m in FIBO_MAPPINGS.iter().filter(|m| m.status == "verified") {
        let path = root.join(m.corpus_file);
        let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("{path:?}: {e}"));
        let sha = format!("{:x}", Sha256::digest(&bytes));
        assert_eq!(sha, m.corpus_sha256, "corpus drift for {} ({})", m.id, m.corpus_file);
        let text = String::from_utf8(bytes).unwrap();
        // The module's own versionIRI is recorded and present.
        assert!(text.contains(m.version_iri), "versionIRI {} not in {}", m.version_iri, m.corpus_file);
        // The IRI is a declared term: rdf:about="&entity;Local".
        let anchor = format!(";{}\"", local_name(m.fibo_iri));
        assert!(
            text.lines().any(|l| l.contains("rdf:about=") && l.contains(&anchor)),
            "{} not declared via rdf:about in {}",
            m.fibo_iri,
            m.corpus_file
        );
        // And the IRI namespace equals module path prefix.
        assert!(m.fibo_iri.starts_with("https://spec.edmcouncil.org/fibo/ontology/"));
        assert!(m.fibo_iri.contains(m.fibo_module));
    }
}

#[test]
fn generated_table_matches_the_rdf_source_and_ids_are_unique() {
    let ttl = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/ontology/payments-fibo/payments-fibo.ttl")).unwrap();
    let rows = ttl.lines().filter(|l| l.contains(" a castle:FiboMapping ;")).count();
    assert_eq!(rows, FIBO_MAPPINGS.len(), "generated table is stale: re-run `ggen sync run` in ontology/payments-fibo");
    let mut ids: Vec<_> = FIBO_MAPPINGS.iter().map(|m| m.id).collect();
    ids.sort_unstable();
    ids.dedup();
    assert_eq!(ids.len(), FIBO_MAPPINGS.len());
    assert!(unverified_terms().is_empty(), "unverified IRIs present: {:?}", unverified_terms());
    let gen = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/ontology/payments-fibo/generated/fibo_generated.rs")).unwrap();
    assert!(gen.starts_with("// GENERATED by ggen"));
}

#[test]
fn every_currency_maps_to_an_iso4217_individual() {
    for c in [Currency::USD, Currency::EUR, Currency::GBP, Currency::JPY, Currency::KWD] {
        let iri = currency_iri(c);
        assert!(iri.ends_with(&format!("ISO4217-CurrencyCodes/{}", c.code())), "{iri}");
        assert!(FIBO_MAPPINGS.iter().any(|m| m.fibo_iri == iri && m.fibo_kind == "Individual"));
    }
}

#[test]
fn amounts_are_exact_decimals_with_currency_exponent_and_no_floats() {
    let usd = monetary_amount_json(&Money::parse_minor("1250", Currency::USD).unwrap());
    assert_eq!(usd[IRI_HAS_AMOUNT]["@value"], "12.50");
    let kwd = monetary_amount_json(&Money::parse_minor("1234567", Currency::KWD).unwrap());
    assert_eq!(kwd[IRI_HAS_AMOUNT]["@value"], "1234.567");
    let jpy = monetary_amount_json(&Money::parse_minor("5000", Currency::JPY).unwrap());
    assert_eq!(jpy[IRI_HAS_AMOUNT]["@value"], "5000");
    assert_eq!(usd["@type"], IRI_MONETARY_AMOUNT);
    assert!(usd[IRI_HAS_AMOUNT]["@value"].is_string(), "amount must not be a JSON number");
}

#[tokio::test]
async fn only_a_really_settled_payment_is_typed_as_a_fibo_payment() {
    let fx = Fixture::new("fibo-settled");
    let adm = fx.admit(fx.effect("470000", "invoice-9821"), "n-1").unwrap();
    let digest = adm.effect().digest().to_string();

    // Reserved (admitted, not yet executed): castle effect, NOT a FIBO Payment.
    let reserved = fx.claims.get(&digest).unwrap().unwrap();
    assert_eq!(claim_type_iri(&reserved), CASTLE_PAYMENT_EFFECT);
    assert_ne!(claim_jsonld(&reserved, None)["@type"], IRI_PAYMENT);

    let exec = execute_payment(adm, &fx.exec_ctx()).await.unwrap();
    assert_eq!(exec.standing, PaymentStanding::Settled);
    let claim = fx.claims.get(&digest).unwrap().unwrap();
    let entry = fx.ledger.lookup(&digest).unwrap().unwrap();
    let node = claim_jsonld(&claim, Some(&entry));

    assert_eq!(node["@type"], IRI_PAYMENT);
    assert_eq!(node[IRI_HAS_PAYMENT_AMOUNT][IRI_HAS_AMOUNT]["@value"], "4700.00");
    assert_eq!(node[IRI_HAS_PAYMENT_AMOUNT][IRI_HAS_CURRENCY]["@id"], IRI_CURRENCY_USD);
    assert_eq!(node["https://chatmangpt.com/ontology/castle#obligation"]["@type"], IRI_PAYMENT_OBLIGATION);
    assert_eq!(node["https://chatmangpt.com/ontology/castle#payerAccount"]["@type"], IRI_PAYER);
    assert_eq!(node["https://chatmangpt.com/ontology/castle#payeeAccount"]["@type"], IRI_PAYEE);
    assert_eq!(node["https://chatmangpt.com/ontology/castle#constructDigest"], entry.construct_digest);
    // Projection is deterministic and carries no authority field.
    assert_eq!(node, claim_jsonld(&claim, Some(&entry)));
    assert!(!node.to_string().contains("grants_authority"));
}

#[tokio::test]
async fn unknown_outcome_and_refused_claims_are_never_fibo_payments() {
    // Refused: insufficient funds.
    let fx = Fixture::with("fibo-nsf", 50, 500_000, 1_000_000);
    let adm = fx.admit(fx.effect("100", "inv-nsf"), "n-1").unwrap();
    let d = adm.effect().digest().to_string();
    let _ = execute_payment(adm, &fx.exec_ctx()).await.unwrap();
    let c = fx.claims.get(&d).unwrap().unwrap();
    assert_eq!(c.state, ClaimState::Refused);
    assert_eq!(claim_jsonld(&c, None)["@type"], CASTLE_PAYMENT_EFFECT);
    // UnknownOutcome state is likewise not a Payment.
    let mut u = c.clone();
    u.state = ClaimState::UnknownOutcome;
    assert_eq!(claim_type_iri(&u), CASTLE_PAYMENT_EFFECT);
}

#[test]
fn fibo_module_sources_are_model_free_and_grant_no_authority() {
    let src = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/src/payments/fibo.rs")).unwrap();
    for banned in ["admit_construct_for_do", "PaymentAdmission {", "ActuationToken {", "execute_powl_with_gym_act"] {
        assert!(!src.contains(banned), "fibo.rs must not touch authority path: {banned}");
    }
}
