#!/usr/bin/env bash
# GENERATED by `ggen sync` from packs/platform-engineers-handbook-ch02-cluster-pack/ontology.ttl
# -- do not edit by hand. App-of-Apps GitOps bootstrap invocation, matching the source and
# path conventions of Ch02's real modules/flux.py (FluxSourceConfig / FluxAppOfAppsManager.
# create_root_application()). Whether this script performs a real bootstrap or a documented
# no-op is bound from pech2:fluxBootstrapped -- never hand-edited here.
set -euo pipefail

CLUSTER_NAME="platform-dev"

echo "Bootstrapping Flux (App-of-Apps) on kind cluster ${CLUSTER_NAME}..."
flux bootstrap git \
  --context "kind-${CLUSTER_NAME}" \
  --url="https://github.com/example-org/platform-dev-gitops" \
  --branch="main" \
  --path="clusters/platform-dev"

echo "Flux bootstrapped on ${CLUSTER_NAME} (repo=https://github.com/example-org/platform-dev-gitops, branch=main, path=clusters/platform-dev)."
