// GENERATED by ggen-marketplace/castle-pack. Do not hand-edit.
export const GENERATED_BINDINGS = [
  { kind: "component", order: 10, identifier: "DfCMGoalInversion", slug: "dfcm-goal-inversion", role: "Derive minimal vulnerability conditions backward from prohibited adversarial goals.", authority: "CONSTRUCT_ONLY", predicate: "", consequence: 0 },
  { kind: "component", order: 20, identifier: "DependencyConstruct", slug: "dependency-construct", role: "Construct counterfactual dependency compromise capabilities and impacted closure.", authority: "CONSTRUCT_ONLY", predicate: "", consequence: 0 },
  { kind: "component", order: 30, identifier: "AutoFDELabPlannerEnsemble", slug: "autofde-lab-planner-ensemble", role: "Fan out admitted planning problems across applicable planner candidates.", authority: "CANDIDATE_ONLY", predicate: "", consequence: 0 },
  { kind: "component", order: 40, identifier: "Construct", slug: "construct", role: "Manufacture candidate worlds, plans, OCEL histories, and artifacts without consequential authority.", authority: "NO_DO", predicate: "", consequence: 0 },
  { kind: "component", order: 50, identifier: "POWLv2Compiler", slug: "powl-v2-compiler", role: "Quotient plan serializations into causal partial-order workflows for replay.", authority: "COMPILE_ONLY", predicate: "", consequence: 0 },
  { kind: "component", order: 60, identifier: "GymActBoundary", slug: "gymact-boundary", role: "Execute only explicitly admitted adversarial tests against owned or authorized systems.", authority: "TEST_ENVELOPE", predicate: "", consequence: 0 },
  { kind: "component", order: 70, identifier: "OCELv2Observation", slug: "ocel-v2-observation", role: "Record object-centric observed execution evidence and replay state.", authority: "OBSERVE_ONLY", predicate: "", consequence: 0 },
  { kind: "component", order: 80, identifier: "BLAKE3ReceiptContract", slug: "blake3-receipt-contract", role: "Bind artifact identity and epistemic standing to BLAKE3-256 content digests.", authority: "EVIDENCE_ONLY", predicate: "", consequence: 0 },
  { kind: "component", order: 90, identifier: "ZeroDayListener", slug: "zero-day-listener", role: "Treat newly admitted dependency capabilities or novel transitions as graph mutations.", authority: "OBSERVE_ONLY", predicate: "", consequence: 0 },
  { kind: "component", order: 100, identifier: "BRCEBoundary", slug: "brce-boundary", role: "Reserve consequential defensive actuation for the bounded receipted DO boundary.", authority: "RECEIPT_BOUND_DO", predicate: "", consequence: 0 },
  { kind: "goal", order: 110, identifier: "UnauthorizedAuthority", slug: "unauthorized-authority", role: "Adversary obtains authority not admitted by policy.", authority: "PROHIBITED", predicate: "goal:unauthorized-authority", consequence: 100 },
  { kind: "goal", order: 120, identifier: "ConfidentialityLoss", slug: "confidentiality-loss", role: "Adversary gains protected information disclosure.", authority: "PROHIBITED", predicate: "goal:confidentiality-loss", consequence: 95 },
  { kind: "goal", order: 130, identifier: "IntegrityLoss", slug: "integrity-loss", role: "Adversary causes unauthorized protected-state mutation.", authority: "PROHIBITED", predicate: "goal:integrity-loss", consequence: 95 },
  { kind: "goal", order: 140, identifier: "AvailabilityLoss", slug: "availability-loss", role: "Adversary prevents a required service outcome.", authority: "PROHIBITED", predicate: "goal:availability-loss", consequence: 90 },
  { kind: "goal", order: 150, identifier: "UnauthorizedPersistence", slug: "unauthorized-persistence", role: "Adversary preserves unauthorized standing across state transitions.", authority: "PROHIBITED", predicate: "goal:unauthorized-persistence", consequence: 90 }
] as const;

export const GENERATED_COMPONENTS = GENERATED_BINDINGS.filter((binding) => binding.kind === "component");
export const DEFAULT_ADVERSARIAL_GOALS = GENERATED_BINDINGS
  .filter((binding) => binding.kind === "goal")
  .map((binding) => ({
    id: binding.slug,
    predicate: binding.predicate,
    consequence: binding.consequence,
  }));
