//! FIBO-typed projection of payments. Vocabulary only: nothing here grants authority or
//! feeds any CONSTRUCT/DO admission path. The IRI table is GENERATED by `ggen sync run` from
//! `ontology/payments-fibo/payments-fibo.ttl` into
//! `ontology/payments-fibo/generated/fibo_generated.rs`; edit the RDF, never the generated file.
//! FIBO has no home for reversal, finality, sanctions or sealed admission; those remain `castle:`.

use serde_json::{json, Value};

use super::claim_store::{Claim, ClaimState};
use super::ledger::LedgerEntry;
use super::money::{Currency, Money};

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/ontology/payments-fibo/generated/fibo_generated.rs"));

pub const CASTLE_NS: &str = "https://chatmangpt.com/ontology/castle#";
pub const CASTLE_PAYMENT_EFFECT: &str = "https://chatmangpt.com/ontology/castle#PaymentEffect";
const CASTLE_MINOR_UNITS: &str = "https://chatmangpt.com/ontology/castle#minorUnits";
const CASTLE_OBLIGATION_ID: &str = "https://chatmangpt.com/ontology/castle#obligationId";
const CASTLE_EFFECT_DIGEST: &str = "https://chatmangpt.com/ontology/castle#effectDigest";
const CASTLE_CONSTRUCT_DIGEST: &str = "https://chatmangpt.com/ontology/castle#constructDigest";
const CASTLE_PAYER: &str = "https://chatmangpt.com/ontology/castle#payerAccount";
const CASTLE_PAYEE: &str = "https://chatmangpt.com/ontology/castle#payeeAccount";
const CASTLE_OBLIGATION: &str = "https://chatmangpt.com/ontology/castle#obligation";

/// ISO 4217 individual for a castle currency. Exhaustive: a new `Currency` variant
/// fails to compile until the RDF source gains its mapping and `ggen sync run` is re-run.
#[must_use]
pub const fn currency_iri(currency: Currency) -> &'static str {
    match currency {
        Currency::USD => IRI_CURRENCY_USD,
        Currency::EUR => IRI_CURRENCY_EUR,
        Currency::GBP => IRI_CURRENCY_GBP,
        Currency::JPY => IRI_CURRENCY_JPY,
        Currency::KWD => IRI_CURRENCY_KWD,
    }
}

/// `fibo-fnd-acc-cur:MonetaryAmount`. `hasAmount` is a FIBO DatatypeProperty, so the amount is
/// an exact decimal string (currency-exponent aware, no floats); minor units ride alongside.
#[must_use]
pub fn monetary_amount_json(money: &Money) -> Value {
    json!({
        "@type": IRI_MONETARY_AMOUNT,
        IRI_HAS_AMOUNT: { "@value": money.to_decimal_string(), "@type": "http://www.w3.org/2001/XMLSchema#decimal" },
        IRI_HAS_CURRENCY: { "@id": currency_iri(money.currency) },
        CASTLE_MINOR_UNITS: money.minor.to_string(),
    })
}

/// Only a settled (Executed) claim is a FIBO `Payment`; everything else stays a castle effect.
#[must_use]
pub fn claim_type_iri(claim: &Claim) -> &'static str {
    if claim.state == ClaimState::Executed {
        IRI_PAYMENT
    } else {
        CASTLE_PAYMENT_EFFECT
    }
}

/// Deterministic JSON-LD-shaped projection of a claim (and, when settled, its ledger entry).
/// The projection carries no `grants_authority`; it is evidence vocabulary, not a capability.
#[must_use]
pub fn claim_jsonld(claim: &Claim, entry: Option<&LedgerEntry>) -> Value {
    let money = Money { minor: claim.amount_minor, currency: claim.currency };
    let mut node = json!({
        "@id": format!("urn:castle:payment:{}", claim.effect_digest),
        "@type": claim_type_iri(claim),
        CASTLE_EFFECT_DIGEST: claim.effect_digest,
        IRI_HAS_PAYMENT_AMOUNT: monetary_amount_json(&money),
        CASTLE_PAYER: { "@id": format!("urn:castle:account:{}", claim.payer), "@type": IRI_PAYER },
        CASTLE_PAYEE: { "@id": format!("urn:castle:account:{}", claim.payee), "@type": IRI_PAYEE },
    });
    if !claim.obligation_id.is_empty() {
        node[CASTLE_OBLIGATION] = json!({
            "@id": format!("urn:castle:obligation:{}", claim.obligation_id),
            "@type": IRI_PAYMENT_OBLIGATION,
            CASTLE_OBLIGATION_ID: claim.obligation_id,
        });
    }
    if let (ClaimState::Executed, Some(e)) = (claim.state, entry) {
        node[CASTLE_CONSTRUCT_DIGEST] = json!(e.construct_digest);
    }
    node
}

#[must_use]
pub fn mapping_for(id: &str) -> Option<&'static FiboMapping> {
    FIBO_MAPPINGS.iter().find(|m| m.id == id)
}

/// Rows whose IRI is not yet corpus-verified. Never projected into output.
#[must_use]
pub fn unverified_terms() -> Vec<&'static FiboMapping> {
    FIBO_MAPPINGS.iter().filter(|m| m.status != "verified").collect()
}
