//! Typed refusals: `Err("REFUSED:<REASON>")` strings, matching the crate convention.

pub const CAPABILITY_NOT_ADMITTED: &str = "REFUSED:PAYMENT_CAPABILITY_NOT_ADMITTED";
pub const PAYLOAD_INVALID: &str = "REFUSED:PAYMENT_PAYLOAD_INVALID";
pub const AMOUNT_NOT_INTEGER: &str = "REFUSED:PAYMENT_AMOUNT_NOT_INTEGER";
pub const AMOUNT_ZERO: &str = "REFUSED:PAYMENT_AMOUNT_ZERO";
pub const AMOUNT_EXCEEDS_CAP: &str = "REFUSED:PAYMENT_AMOUNT_EXCEEDS_CAP";
pub const CURRENCY_UNSUPPORTED: &str = "REFUSED:PAYMENT_CURRENCY_UNSUPPORTED";
pub const ACCOUNT_NOT_ALLOWED: &str = "REFUSED:PAYMENT_ACCOUNT_NOT_ALLOWED";
pub const SAME_ACCOUNT: &str = "REFUSED:PAYMENT_SAME_ACCOUNT";
pub const BUDGET_EXCEEDED: &str = "REFUSED:PAYMENT_BUDGET_EXCEEDED";
pub const NO_SPEND_POLICY: &str = "REFUSED:NO_SPEND_POLICY_FOR_PRINCIPAL";
pub const OUTCOME_UNKNOWN: &str = "REFUSED:PAYMENT_OUTCOME_UNKNOWN";
pub const ALREADY_SETTLED: &str = "REFUSED:PAYMENT_ALREADY_SETTLED";
pub const IN_FLIGHT: &str = "REFUSED:PAYMENT_IN_FLIGHT";
pub const INSUFFICIENT_FUNDS: &str = "REFUSED:PAYMENT_INSUFFICIENT_FUNDS";
pub const LEDGER_UNAVAILABLE: &str = "REFUSED:PAYMENT_LEDGER_UNAVAILABLE";
pub const REVERSAL_ORIGINAL_NOT_EXECUTED: &str = "REFUSED:PAYMENT_REVERSAL_ORIGINAL_NOT_EXECUTED";
pub const REVERSAL_EXCEEDS_ORIGINAL: &str = "REFUSED:PAYMENT_REVERSAL_EXCEEDS_ORIGINAL";
pub const REVERSAL_MISMATCH: &str = "REFUSED:PAYMENT_REVERSAL_MISMATCH";
pub const RECONCILIATION_DRIFT: &str = "REFUSED:RECONCILIATION_DRIFT";
pub const CLAIM_STORE_FAILED: &str = "BLOCKED:PAYMENT_CLAIM_STORE_FAILED";

pub type PayResult<T> = Result<T, String>;

pub fn refuse<T>(code: &str) -> PayResult<T> {
    Err(code.to_string())
}
